"""Initial Migration

Revision ID: 1cb6dc389c66
Revises: 99b9567d1940
Create Date: 2019-10-25 05:26:13.110717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cb6dc389c66'
down_revision = '99b9567d1940'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('downvotes', sa.Column('downvote', sa.Integer(), nullable=True))
    op.add_column('upvotes', sa.Column('upvote', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upvotes', 'upvote')
    op.drop_column('downvotes', 'downvote')
    # ### end Alembic commands ###
