"""Initial Migration

Revision ID: 574d2bc0264a
Revises: bc7d5682343c
Create Date: 2019-10-21 23:28:35.041674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '574d2bc0264a'
down_revision = 'bc7d5682343c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitch', 'date')
    # ### end Alembic commands ###
