"""Initial Migration

Revision ID: 968e7213e8c5
Revises: bfd5865ae30c
Create Date: 2019-10-18 17:42:27.441632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '968e7213e8c5'
down_revision = 'bfd5865ae30c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
